apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nonexisting
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
        newlabel: value
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        env:
        - name: WHOCARES
          value: yeah
        ports:
        - containerPort: 80

